name: Build and push SeedWorks

on:
  push:
    branches:
      - master
    paths:
      - Source/*
      - .github/workflows/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Build with dotnet
      run: dotnet build Source/Hive.SeedWorks.csproj --configuration Release
    - name: Project pack
      run : dotnet pack Source/Hive.SeedWorks.csproj --configuration Release --output bin/nupkgs
    - name: Nuget push
      run : dotnet nuget push "bin/nupkgs/*.nupkg" -k ${GITHUB_TOKEN} --skip-duplicate --no-symbols #--source "https://github.com/Ekstrem/Hive"
      env : GITHUB_TOKEN: ${{ secrets.PACK_ACCESS }}
      # run : dotnet nuget push "bin/nupkgs/*" --source "github"
